spring:
  application:
    name: FALO_SKELETON
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      jdbc:
        time_zone: ${DB_TIME_ZONE:Asia/Ho_Chi_Minh}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8082/eureka

# Optional: CORS if accessed from a frontend
# spring:
#   web:
#     cors:
#       allowed-origins: "*"
#       allowed-methods: "*"
#       allowed-headers: "*"