spring:
  application:
    name: CAKE-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      jdbc:
        time_zone: ${DB_TIME_ZONE:Asia/Ho_Chi_Minh}

server:
  port: 8081

grpc:
  server:
    port: 9091
    security:
      enabled: false

jwt:
  access-token:
    expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token:
    expiration: ${REFRESH_TOKEN_EXPIRATION}
  secret-key: ${SECRET_KEY}

