version: '3.8'
services:
  gateway-example-dev:
    build:
      context: .devcontainer
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    container_name: gateway-example-dev
    networks:
      - devnet

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - devnet

  gatewaydb:
    container_name: gateway-db
    image: postgres
    restart: always
    volumes:
      - gateway-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gatewaydb
      - POSTGRES_USER=gateway
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - devnet

volumes:
  gateway-db-data:
    
networks:
  devnet:
    external: true