version: '3.8'
services:
  gateway-example-dev:
    build:
      context: .devcontainer
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    container_name: gateway-example-dev
    networks:
      - devnet

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - devnet

networks:
  devnet:
    external: true