server:
  port: 8082
spring:
  application:
    name: API-GATEWAY-SERVICE
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**

        - id: CAKE-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/cake/**
          filters:
            - name: AuthFilter
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false

grpc:
  auth:
    host: localhost
    port: 9090