server:
  port: 8082
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**

        - id: CAKE-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/cake/**
          filters:
            - name: AuthFilter

eureka:
  client:
    register-with-eureka: false  # Don't register itself
    fetch-registry: true         # Can still fetch other services

custom:
  auth:
    get-permission-uri: http://localhost:8080/auth/permission